seed: 42
device: "cuda"

data:
  path: "user_data/data/binance/BTC_USDT-1h.feather"
  window: 72
  lookback_days: 1825
  finetune_days: 180

tft:
  hidden_size: 64
  attention_heads: 4
  dropout: 0.1
  learning_rate: 0.0001
  max_epochs: 100
  batch_size: 64
  encoder_length: 72
  early_stopping:
    patience: 5
    min_delta: 1e-6
  scheduler:
    factor: 0.5
    patience: 2
  grad_clip: 0.5
  train_split: 0.85

ppo:
  learning_rate: 0.00003
  gamma: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  batch_size: 512
  n_steps: 2048
  timesteps: 2000000

optuna:
  trials: 15
  timesteps: 200000
  direction: maximize

logging:
  wandb_project: "TFT_PPO_Trader"
  wandb_entity: "quant-research-team"
