# user_data/TFT_PPO_Training/configs/optuna_config.yml
optuna:
  study_name: "PPO_TFT_KPI_Optimization"
  direction: "maximize"
  storage: "sqlite:///user_data/TFT_PPO_Training/logs/optuna_studies/ppo_tft.db"
  n_trials: 50
  timeout: 28800
  n_jobs: 1
  eval_freq: 25000
  eval_episodes: 5
  sampler:
    type: "TPESampler"
    seed: 42
  pruner:
    type: "MedianPruner"
    n_startup_trials: 8
    n_warmup_steps: 3
  search_space:
    learning_rate: { type: "loguniform", low: 1.0e-5, high: 5.0e-4 } 
    gamma:         { type: "uniform",    low: 0.98,  high: 0.999 }
    clip_range:    { type: "uniform",    low: 0.15,  high: 0.3 }     
    ent_coef:      { type: "uniform",    low: 0.01,  high: 0.08 }    
    batch_size:    { type: "categorical", choices: [256, 512, 1024] }
    vf_coef:       { type: "uniform",    low: 0.5,   high: 1.0 }    
    max_grad_norm: { type: "uniform",    low: 0.3,   high: 0.7 }    
